### ISSUE TITLE
EPIC: Prisma 2 and existing database

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2#156]
This issue aims to act as the parent issue for collecting issues around the topic of using Prisma 2 with existing projects. 

**Lift**:
- [ ] 1) Ignore `Migration` table in introspection result https://github.com/prisma/specs/issues/52

**Robustness**: 
- [x] 2) Graceful error handling #13 
- [x] 3) Field support ("char") https://github.com/prisma/lift/issues/17
- [x] 4) Introspect should required the Prisma schema file #11
- [x] 5) #73 
- [x] 6) #14 

**Feature Parity**:
- [ ] 7) SQLite support #51

**More**:
- [ ] Support for introspecting tables without an ID field #175
- [ ] Introspection does not "auto" resolve ambiguous relations #176
- [ ] Make introspection work with Discourse DB #177

**Comment by sorenbs** [comment]
Thanks for collecting these @divyenduz!

I would like to push for fixing as many of these this week as possible. My understanding is that 
1) is a quick one
2) is implemented correctly. Features that are not implemented does not show up in the Prisma Schema. Features that are implemented but with partial completeness will comment out fields that are not supported.
3) This is a partially implemented feature. So this field should have been commented out in the introspection. It might be simpler to just wait a few weeks until we introduce support for `char` columns. @mavilein can make a call here.
4) This is a quick one
5) Is a medium sized work Item for @timsuchanek . Tim - is this sufficiently specced?
6) @mavilein - is this an issue with Introspection or migration? We might want to wait until we have introspection rewritten in Rust.
7) This will have to wait until we have rewritten introspection in Rust.

**Comment by timsuchanek** [comment]
Yep agree, so 4 & 5 are things I can tackle, 1) is for @ejoebstl, the rest is something for @mavilein.

**Comment by divyenduz** [comment]
Support for introspecting tables without an ID field #175

**Comment by janpio** [comment]
Further progress is being tracked in https://github.com/orgs/prisma/projects/13
