### ISSUE TITLE
[EPIC] Move prisma 2 rust code from `prisma` repo to somewhere else

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma2#390]
Currently the repository `prisma/prisma` contains the source code for Prisma 1 as well as Prisma 2. We want to move the parts written in Rust (the engines) somewhere else.

The following steps need be done to accomplish this:
- [x] get rid of mixed mode integration tests via `native-bridge`
- [x] make `prisma-rs` independent of the Prisma 1 `server/.envrc`
- [x] separate pipelines for Prisma 1 and 2 (although still in the same repo)
- [x] move `prisma-rs` to be determined location and repo

**Comment by janpio** [comment]
Discussion about future location (which might not be permanent) are currently in progress.

**Comment by dpetrick** [comment]
It's easier if the steps are the following:
- [x] Remove Scala and Rust code bindings (as already stated in your list)
- [ ] Cleanup Prisma 1 codebase.
- [ ] Freeze alpha branch after merging all outstanding PRs that touch the Rust code.
- [ ] Move `prisma-rs` to a new repo. Naming doesn't matter from an ops perspective. All that matters is that is's a different repo.
- [ ] Clone the `build-cli` and throw out all Prisma 1 related tasks. Clean up Prisma 1 `build-cli`.
- [ ] Create new pipeline.

The list sounds more impressive than it actually is. The biggest hurdle at the moment is merely getting all code on alpha and freezing the code.

**Comment by janpio** [comment]
@sorenbs will create the repo for you to move the code soon-ish (💤). It will have a temporary name that might be subject to discussion in the future - but for now it gives you a way to move forward.

**Comment by dpetrick** [comment]
Code move is done. New repository is: https://github.com/prisma/prisma-engine.

**Comment by janpio** [comment]
@mavilein Please confirm that everything you thought of was taken care of here and just close this issue ans confirmation.
