### ISSUE TITLE
EPIC: Platform support

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2#533]
This is an umbrella issue for the Prisma rust binary support on various platforms.

- [x] Mac
- [x] #4 Windows
- [x] Debian & Ubuntu
- [x] CentOS, Fedora
- [x] Lambda, Netlify functions, Now by Zeit
- [x] #86, #157 Netlify (use new build image!)
- [ ] https://github.com/prisma/prisma2/issues/702 Alpine Linux
- [x] prisma/prisma-engine#37 (major issue) debian-based binaries with different libssl combinations for debian & ubuntu and respective distributions

**Comment by divyenduz** [comment]
Everything else is done, we track alpine separately here: https://github.com/prisma/prisma2/issues/702
